services:
  server:
    init: true
    container_name: ${PROJECT_NAME}_server
    image: nginx:latest
    ports:
      - "${NGINX_UI_EXPOSE_PORT}:8000"
      - "${NGINX_SOCKET_EXPOSE_PORT}:8010"
      - "${NGINX_API_EXPOSE_PORT}:8020"
      - "${DOCS_EXPOSE_PORT}:8030"
    env_file:
      - ./envs/.nginx.env
    volumes:
      - ./server/conf.template:/etc/nginx/templates/default.conf.template
      - ./server/nginx.conf:/etc/nginx/nginx.conf
      - ../src/ui/dist:/usr/share/nginx/html
    command: [nginx-debug, "-g", "daemon off;"]
    depends_on:
      - ui
      - api
      - socket
    networks:
      - net
    restart: always

  ui:
    init: true
    container_name: ${PROJECT_NAME}_ui
    build:
      context: ../src
      dockerfile: ui/Dockerfile
    env_file:
      - ./envs/.ui.env
    working_dir: /app
    command: yarn build
    volumes:
      - ../src/ui/src:/app/src
      - ../src/ui/dist:/app/dist:rw
      - ../src/shared/ts:/shared/ts
      - ../src/ui/vite.config.ts:/app/vite.config.ts
      - ../src/ui/tailwind.config.js:/app/tailwind.config.js
      - ../src/ui/postcss.config.js:/app/postcss.config.js
    networks:
      - net

  api: &api
    init: true
    container_name: ${PROJECT_NAME}_api
    build:
      context: ../
      target: with-cron
    env_file:
      - ./envs/.api.env
    environment:
      WORKER: main
    working_dir: /app
    command: uv run --no-sync ${PROJECT_NAME} run --workers ${API_WORKERS_COUNT:-1}
    stop_grace_period: 16m
    volumes:
      - ../src/api/${PROJECT_NAME}:/app/src/api/${PROJECT_NAME}
      - ../src/shared/py:/app/src/shared/py
      - shared-py-venv:/app/shared/py/.venv
      - ../src/resources:/app/src/resources
      - ../pyproject.toml:/app/pyproject.toml
      - ../uv.lock:/app/uv.lock
      - ../README.md:/app/README.md
      - ../LICENSE:/app/LICENSE
      - ../alembic.ini:/app/alembic.ini
      - ../local:/app/local
      - ../scripts/run_bot_cron.sh:/app/scripts/run_bot_cron.sh:x
      - ../scripts/run_notification_cron.sh:/app/scripts/run_notification_cron.sh:x
      - ./volumes/.vault-credentials:/app/.vault-credentials:ro
    depends_on:
      - db-bouncer
      - kafka0
      - kafka1
      - kafka2
      - redis
      - redis-broker
    networks:
      - net
    restart: always

  celeryworker:
    <<: *api
    init: true
    container_name: ${PROJECT_NAME}_celeryworker
    build:
      context: ../
      target: base
    command: uv run --no-sync ${PROJECT_NAME} run:broker
    stop_grace_period: 16m

  socket:
    init: true
    container_name: ${PROJECT_NAME}_socket
    build:
      context: ../src
      dockerfile: socket/Dockerfile
    env_file:
      - ./envs/.socket.env
    working_dir: /app
    stop_grace_period: 16m
    volumes:
      - ../src/socket/package.json:/app/package.json
      - ../src/socket/yarn.lock:/app/yarn.lock
      - ../src/socket/src:/app/src
      - ../src/shared/ts:/shared/ts
      - ../src/resources:/app/resources
      - ../.env:/app/.env
      - ./volumes/.vault-credentials:/app/.vault-credentials:ro
    depends_on:
      - db-bouncer
      - kafka0
      - kafka1
      - kafka2
      - graph
      - redis
      - redis-broker
    networks:
      - net
    restart: always

  graph:
    init: true
    container_name: ${PROJECT_NAME}_graph
    build:
      context: ../src
      dockerfile: graph/Dockerfile
    env_file:
      - ./envs/.graph.env
    working_dir: /app/src/graph
    command: uv run --no-sync graph run --workers ${GRAPH_WORKERS_COUNT:-1}
    stop_grace_period: 16m
    volumes:
      - ../src/graph/${PROJECT_NAME}_graph:/app/src/graph/${PROJECT_NAME}_graph
      - ../src/shared/py:/app/src/shared/py
      - shared-py-venv:/app/shared/py/.venv
      - ../src/graph/pyproject.toml:/app/src/graph/pyproject.toml
      - ../src/graph/uv.lock:/app/src/graph/uv.lock
      - ../local:/app/local
      - ./volumes/.vault-credentials:/app/.vault-credentials:ro
    depends_on:
      - db-bouncer
      - kafka0
      - kafka1
      - kafka2
      - api
      - redis
      - redis-broker
    networks:
      - net
    restart: always

volumes:
  shared-py-venv:
    driver: local
