services:
  vault:
    init: true
    container_name: ${PROJECT_NAME}_vault
    image: openbao/openbao:latest
    ports:
      - "8200:8200"
    environment:
      - BAO_LOCAL_CONFIG={"listener":{"tcp":{"address":"0.0.0.0:8200","tls_disable":true}},"storage":{"file":{"path":"/openbao/file"}},"api_addr":"http://0.0.0.0:8200","disable_mlock":true,"ui":true}
      - ROOT_TOKEN=${KEY_PROVIDER_OPENBAO_ROOT_TOKEN}
      - PROJECT_NAME=${PROJECT_NAME}
    volumes:
      - ./vault/entrypoint.sh:/entrypoint.sh:ro
      - ${VAULT_DATA_MOUNT:-./volumes/vault/file}:/openbao/file
      - ./volumes/vault/logs:/openbao/logs
      - ./volumes/vault/config:/bao/config
      - ./volumes/.vault-credentials:/openbao/.vault-credentials
      - ./volumes/vault-secret.json:/openbao/vault-secret.json
    cap_add:
      - IPC_LOCK
    command: ["sh", "/entrypoint.sh"]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "test -s /openbao/.vault-credentials && wget -qO- 'http://127.0.0.1:8200/v1/sys/health?standbyok=true' >/dev/null",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - net
    restart: always

volumes:
  vault_data:
    external: true
    name: ${PROJECT_NAME}_vault_data
