"""empty message

Revision ID: 784b135adf9c
Revises: d308f2a9221c
Create Date: 2026-09-13 02:56:40.546919

"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from langboard_shared.core.db.ColumnTypes import EnumLikeType
from langboard_shared.core.db.ColumnTypes import SnowflakeIDType
from langboard_shared.domain.models.OllamaModelPull import OllamaModelPullStatus

# revision identifiers, used by Alembic.
revision: str = '784b135adf9c'
down_revision: Union[str, None] = 'd308f2a9221c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ollama_model_pull',
    sa.Column('id', SnowflakeIDType, autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('status', EnumLikeType(OllamaModelPullStatus), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('percent', sa.Float(), nullable=False),
    sa.Column('status_text', sa.String(), nullable=True),
    sa.Column('failure_reason', sa.TEXT(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ollama_model_pull')),
    sa.UniqueConstraint('model_name', name=op.f('uq_ollama_model_pull_model_name'))
    )
    op.create_index(op.f('ix_ollama_model_pull_status'), 'ollama_model_pull', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ollama_model_pull_status'), table_name='ollama_model_pull')
    op.drop_table('ollama_model_pull')
    # ### end Alembic commands ###
