"""empty message

Revision ID: 3a3d6b9eb3c2
Revises: 97671190258e
Create Date: 2026-09-13 08:56:43.854311

"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from langboard_shared.core.db.ColumnTypes import SnowflakeIDType

# revision identifiers, used by Alembic.
revision: str = '3a3d6b9eb3c2'
down_revision: Union[str, None] = '97671190258e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('internal_bot_run', sa.Column('ai_chat_history_id', SnowflakeIDType, nullable=True))
    op.create_foreign_key(op.f('fk_internal_bot_run_ai_chat_history_id_chat_history'), 'internal_bot_run', 'chat_history', ['ai_chat_history_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_internal_bot_run_ai_chat_history_id_chat_history'), 'internal_bot_run', type_='foreignkey')
    op.drop_column('internal_bot_run', 'ai_chat_history_id')
    # ### end Alembic commands ###
