"""empty message

Revision ID: 58c803491e17
Revises: da39f306364b
Create Date: 2026-09-12 23:43:19.417257

"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58c803491e17'
down_revision: Union[str, None] = 'da39f306364b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_notification', sa.Column('web_fanout_pending', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_user_notification_web_fanout_pending'), 'user_notification', ['web_fanout_pending'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_notification_web_fanout_pending'), table_name='user_notification')
    op.drop_column('user_notification', 'web_fanout_pending')
    # ### end Alembic commands ###
