"""empty message

Revision ID: 814f01ba3dd1
Revises: f32a8519c205
Create Date: 2026-10-04 18:01:59.807751

"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '814f01ba3dd1'
down_revision: Union[str, None] = 'f32a8519c205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_activity', sa.Column('email_fanout_pending', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_project_activity_email_fanout_pending'), 'project_activity', ['email_fanout_pending'], unique=False)
    op.add_column('project_wiki_activity', sa.Column('email_fanout_pending', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_project_wiki_activity_email_fanout_pending'), 'project_wiki_activity', ['email_fanout_pending'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_wiki_activity_email_fanout_pending'), table_name='project_wiki_activity')
    op.drop_column('project_wiki_activity', 'email_fanout_pending')
    op.drop_index(op.f('ix_project_activity_email_fanout_pending'), table_name='project_activity')
    op.drop_column('project_activity', 'email_fanout_pending')
    # ### end Alembic commands ###
