"""empty message

Revision ID: d7c1d9948444
Revises: 58c803491e17
Create Date: 2026-09-13 01:35:22.554912

"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from langboard_shared.core.db.ColumnTypes import EnumLikeType
from langboard_shared.core.db.ColumnTypes import SnowflakeIDType
from langboard_shared.domain.models.NotificationEmailDelivery import NotificationEmailDeliveryStatus
from langboard_shared.domain.models.UserNotification import NotificationType

# revision identifiers, used by Alembic.
revision: str = 'd7c1d9948444'
down_revision: Union[str, None] = '58c803491e17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_email_delivery',
    sa.Column('id', SnowflakeIDType, autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notification_id', SnowflakeIDType, nullable=False),
    sa.Column('receiver_id', SnowflakeIDType, nullable=False),
    sa.Column('notification_type', EnumLikeType(NotificationType), nullable=False),
    sa.Column('scope_models', sa.JSON(), nullable=True),
    sa.Column('recipient_email', sa.String(), nullable=False),
    sa.Column('preferred_lang', sa.String(), nullable=False),
    sa.Column('template_name', sa.String(), nullable=False),
    sa.Column('formats', sa.JSON(), nullable=False),
    sa.Column('status', EnumLikeType(NotificationEmailDeliveryStatus), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], name=op.f('fk_notification_email_delivery_receiver_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_email_delivery')),
    sa.UniqueConstraint('notification_id', name=op.f('uq_notification_email_delivery_notification_id'))
    )
    op.create_index(op.f('ix_notification_email_delivery_receiver_id'), 'notification_email_delivery', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_notification_email_delivery_status'), 'notification_email_delivery', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_email_delivery_status'), table_name='notification_email_delivery')
    op.drop_index(op.f('ix_notification_email_delivery_receiver_id'), table_name='notification_email_delivery')
    op.drop_table('notification_email_delivery')
    # ### end Alembic commands ###
