"""add durable work event dispatch state

Revision ID: ffefabc64037
Revises: da39f306364b
Create Date: 2026-09-11 02:20:18.711841

"""

from typing import Sequence, Union
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "ffefabc64037"
down_revision: Union[str, None] = "da39f306364b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_notification",
        sa.Column("web_visible", sa.Boolean(), server_default=sa.true(), nullable=False),
    )
    op.add_column("user_notification", sa.Column("work_event_dispatched_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_notification", "work_event_dispatched_at")
    op.drop_column("user_notification", "web_visible")
    # ### end Alembic commands ###
