"""empty message

Revision ID: 97671190258e
Revises: 784b135adf9c
Create Date: 2026-09-13 06:57:25.207015

"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from langboard_shared.core.db.ColumnTypes import EnumLikeType
from langboard_shared.core.db.ColumnTypes import SnowflakeIDType
from langboard_shared.domain.models.InternalBotRun import InternalBotRunKind
from langboard_shared.domain.models.InternalBotRun import InternalBotRunStatus

# revision identifiers, used by Alembic.
revision: str = '97671190258e'
down_revision: Union[str, None] = '784b135adf9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internal_bot_run',
    sa.Column('id', SnowflakeIDType, autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('request_key', sa.String(), nullable=False),
    sa.Column('request_digest', sa.String(), nullable=False),
    sa.Column('client_task_id', sa.String(), nullable=False),
    sa.Column('user_id', SnowflakeIDType, nullable=False),
    sa.Column('project_id', SnowflakeIDType, nullable=False),
    sa.Column('internal_bot_id', SnowflakeIDType, nullable=False),
    sa.Column('chat_session_id', SnowflakeIDType, nullable=True),
    sa.Column('chat_history_id', SnowflakeIDType, nullable=True),
    sa.Column('kind', EnumLikeType(InternalBotRunKind), nullable=False),
    sa.Column('status', EnumLikeType(InternalBotRunStatus), nullable=False),
    sa.Column('scope_table', sa.String(), nullable=False),
    sa.Column('scope_uid', sa.String(), nullable=True),
    sa.Column('graph_session_id', sa.String(), nullable=True),
    sa.Column('graph_thread_id', sa.String(), nullable=True),
    sa.Column('request_payload', sa.JSON(), nullable=False),
    sa.Column('output_text', sa.TEXT(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['chat_history_id'], ['chat_history.id'], name=op.f('fk_internal_bot_run_chat_history_id_chat_history'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_session.id'], name=op.f('fk_internal_bot_run_chat_session_id_chat_session'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['internal_bot_id'], ['internal_bot.id'], name=op.f('fk_internal_bot_run_internal_bot_id_internal_bot'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_internal_bot_run_project_id_project'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_internal_bot_run_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_internal_bot_run')),
    sa.UniqueConstraint('request_key', name=op.f('uq_internal_bot_run_request_key'))
    )
    op.create_index(op.f('ix_internal_bot_run_project_id'), 'internal_bot_run', ['project_id'], unique=False)
    op.create_index(op.f('ix_internal_bot_run_status'), 'internal_bot_run', ['status'], unique=False)
    op.create_index(op.f('ix_internal_bot_run_user_id'), 'internal_bot_run', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_internal_bot_run_user_id'), table_name='internal_bot_run')
    op.drop_index(op.f('ix_internal_bot_run_status'), table_name='internal_bot_run')
    op.drop_index(op.f('ix_internal_bot_run_project_id'), table_name='internal_bot_run')
    op.drop_table('internal_bot_run')
    # ### end Alembic commands ###
