"""align project template name index

Revision ID: da39f306364b
Revises: 91f7b2c4d8e6
Create Date: 2026-09-08 12:27:57.461934

"""

from typing import Sequence, Union
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'da39f306364b'
down_revision: Union[str, None] = '91f7b2c4d8e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_template_name'), table_name='project_template')
    op.create_index(op.f('ix_project_template_name'), 'project_template', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_template_name'), table_name='project_template')
    op.create_index(op.f('ix_project_template_name'), 'project_template', ['name'], unique=False)
    # ### end Alembic commands ###
