"""empty message

Revision ID: f32a8519c205
Revises: 3a3d6b9eb3c2
Create Date: 2026-10-04 17:18:20.321137

"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from langboard_shared.core.db.ColumnTypes import EnumLikeType
from langboard_shared.core.db.ColumnTypes import SnowflakeIDType
from langboard_shared.domain.models.NotificationEmailDelivery import NotificationEmailDeliveryStatus

# revision identifiers, used by Alembic.
revision: str = 'f32a8519c205'
down_revision: Union[str, None] = '3a3d6b9eb3c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_activity_email_delivery',
    sa.Column('id', SnowflakeIDType, autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('project_id', SnowflakeIDType, nullable=False),
    sa.Column('activity_table', sa.String(), nullable=False),
    sa.Column('activity_id', SnowflakeIDType, nullable=False),
    sa.Column('recipient_email', sa.String(), nullable=False),
    sa.Column('status', EnumLikeType(NotificationEmailDeliveryStatus), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.TEXT(), nullable=True),
    sa.Column('review_note', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_project_activity_email_delivery_project_id_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_activity_email_delivery')),
    sa.UniqueConstraint('activity_table', 'activity_id', 'recipient_email', name='uq_project_activity_email_delivery_activity_recipient')
    )
    op.create_index(op.f('ix_project_activity_email_delivery_project_id'), 'project_activity_email_delivery', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_activity_email_delivery_status'), 'project_activity_email_delivery', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_activity_email_delivery_status'), table_name='project_activity_email_delivery')
    op.drop_index(op.f('ix_project_activity_email_delivery_project_id'), table_name='project_activity_email_delivery')
    op.drop_table('project_activity_email_delivery')
    # ### end Alembic commands ###
