"""empty message

Revision ID: 0cc6abc4b020
Revises: 814f01ba3dd1
Create Date: 2026-10-04 18:17:56.502447

"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cc6abc4b020'
down_revision: Union[str, None] = '814f01ba3dd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_activity', sa.Column('email_fanout_retry_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('project_wiki_activity', sa.Column('email_fanout_retry_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_wiki_activity', 'email_fanout_retry_at')
    op.drop_column('project_activity', 'email_fanout_retry_at')
    # ### end Alembic commands ###
