"""empty message

Revision ID: d308f2a9221c
Revises: d7c1d9948444
Create Date: 2026-09-13 02:10:41.723803

"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd308f2a9221c'
down_revision: Union[str, None] = 'd7c1d9948444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_email_delivery', sa.Column('review_note', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_email_delivery', 'review_note')
    # ### end Alembic commands ###
