const API = {
    AUTH: {
        PROVIDER: "/auth/provider",
        EMAIL: "/auth/email",
        SIGN_IN: "/auth/signin",
        SIGN_OUT: "/auth/signout",
        REFRESH: "/auth/refresh",
        ABOUT_ME: "/auth/me",
        OIDC: {
            LOGIN: "/auth/oidc/login",
            CALLBACK: "/auth/oidc/callback",
            LOGOUT: "/auth/oidc/logout",
        },
        RECOVERY: {
            SEND_LINK: "/auth/recovery/send",
            VALIDATE: "/auth/recovery/validate",
            RESET: "/auth/recovery/reset",
        },
        SIGN_UP: {
            SEND_LINK: "/auth/signup",
            ACTIVATE: "/auth/signup/activate",
            EXISTS_EMAIL: "/auth/signup/exist/email",
            RESEND_LINK: "/auth/signup/resend",
        },
    },
    ACCOUNT: {
        GET_SUBEMAILS: "/account/subemails",
        UPDATE_PROFILE: "/account/profile",
        CHANGE_PASSWORD: "/account/password",
        UPDATE_PREFERRED_LANGUAGE: "/account/preferred-language",
        EMAIL: {
            CRUD: "/account/email",
            VERIFY: "/account/email/verify",
        },
        USER_GROUP: {
            CREATE: "/account/group",
            CHANGE_NAME: "/account/group/{group_uid}/name",
            UPDATE_ASSIGNED_EMAILS: "/account/group/{group_uid}/emails",
            DELETE: "/account/group/{group_uid}",
        },
    },
    BATCH: "/batch",
    NOTIFICATION: {
        GET_LIST: "/notifications",
        SETTINGS: {
            ALL: "/notification/settings/all",
            TYPE: "/notification/settings/type",
            ALL_PROJECT: "/notification/settings/project",
            PROJECT: "/notification/settings/project/{uid}",
            ALL_COLUMN: "/notification/settings/column",
            COLUMN: "/notification/settings/project/{uid}/column/{project_column_uid}",
            ALL_CARD: "/notification/settings/card",
            CARD: "/notification/settings/project/{uid}/card/{card_uid}",
            ALL_WIKI: "/notification/settings/wiki",
            WIKI: "/notification/settings/project/{uid}/wiki/{wiki_uid}",
        },
    },
    ACTIVITIY: {
        USER: "/activity/user",
        PROJECT: "/activity/project/{uid}",
        PROJECT_COLUMN: "/activity/project/{uid}/column/{project_column_uid}",
        CARD: "/activity/project/{uid}/card/{card_uid}",
        PROJECT_WIKI: "/activity/project/{uid}/wiki/{wiki_uid}",
    },
    DASHBOARD: {
        ALL_STARRED_PROJECTS: "/dashboard/user/projects/starred",
        PROJECTS: "/dashboard/projects",
        TOGGLE_STAR_PROJECT: "/dashboard/projects/{uid}/star",
        CREATE_PROJECT: "/dashboard/projects/new",
        CARDS: "/dashboard/cards",
        TRACKING: "/dashboard/tracking",
    },
    BOARD: {
        GET: "/board/{uid}",
        DETAILS: "/board/{uid}/details",
        GET_INVITATION: "/project/invite/details/{token}",
        IS_AVAILABLE: "/board/{uid}/available",
        IS_PROJECT_ASSIGNEE: "/board/{uid}/is-assigned/{assignee_uid}",
        GET_CARDS: "/board/{uid}/cards",
        MEMBER_CANDIDATES: "/board/{uid}/member-candidates",
        UPDATE_ASSIGNED_USERS: "/board/{uid}/assigned-users",
        UNASSIGN_ASSIGNEE: "/board/{uid}/unassign/{assignee_uid}",
        ACCEPT_INVITATION: "/project/invite/accept",
        DECLINE_INVITATION: "/project/invite/decline",
        CHAT: {
            GET_SESSIONS: "/board/{uid}/chat/sessions",
            GET_MESSAGES: "/board/{uid}/chat/session/{session_uid}",
            UPDATE_SESSION: "/board/{uid}/chat/session/{session_uid}",
            DELETE_SESSION: "/board/{uid}/chat/session/{session_uid}",
            UPLOAD: "/board/{uid}/chat/upload",
            TEMPLATE: {
                GET_LIST: "/board/{uid}/chat/templates",
                CREATE: "/board/{uid}/chat/template",
                UPDATE: "/board/{uid}/chat/template/{template_uid}",
                DELETE: "/board/{uid}/chat/template/{template_uid}",
            },
        },
        GRAPH_APPROVAL: {
            GET_LIST: "/board/{uid}/graph-approvals",
            COUNT: "/board/{uid}/graph-approvals/count",
            APPROVE: "/board/{uid}/graph-approval/{approval_uid}/approve",
            REJECT: "/board/{uid}/graph-approval/{approval_uid}/reject",
        },
        ORCHESTRATION: {
            APPLY_WORKFLOW_TEMPLATE: "/board/{uid}/orchestration/workflow-template",
            CREATE_TASK: "/board/{uid}/orchestration/tasks",
            RECORD_VERIFICATION: "/board/{uid}/orchestration/card/{card_uid}/verification",
            RECORD_RUN: "/board/{uid}/orchestration/card/{card_uid}/run",
            RECORD_SUGGESTIONS: "/board/{uid}/orchestration/card/{card_uid}/suggestions",
            CREATE_SUGGESTION_TASK: "/board/{uid}/orchestration/card/{card_uid}/suggestion-task",
            RECORD_BYPASS: "/board/{uid}/orchestration/card/{card_uid}/bypass",
        },
        COPY_AS_TEMPLATE: "/board/{uid}/settings/copy-as-template",
        COLUMN: {
            CREATE: "/board/{uid}/column",
            CHANGE_NAME: "/board/{uid}/column/{project_column_uid}/name",
            CHANGE_ORDER: "/board/{uid}/column/{project_column_uid}/order",
            DELETE: "/board/{uid}/column/{project_column_uid}",
        },
        CARD: {
            CREATE: "/board/{uid}/card",
            CHANGE_ORDER: "/board/{uid}/card/{card_uid}/order",
            GET_DETAILS: "/board/{uid}/card/{card_uid}",
            CHANGE_DETAILS: "/board/{uid}/card/{card_uid}/details",
            UPDATE_ASSIGNED_USERS: "/board/{uid}/card/{card_uid}/assigned-users",
            UPDATE_LABELS: "/board/{uid}/card/{card_uid}/labels",
            UPDATE_RELATIONSHIPS: "/board/{uid}/card/{card_uid}/relationships",
            ARCHIVE: "/board/{uid}/card/{card_uid}/archive",
            DELETE: "/board/{uid}/card/{card_uid}",
            ATTACHMENT: {
                UPLOAD: "/board/{uid}/card/{card_uid}/attachment",
                CHANGE_NAME: "/board/{uid}/card/{card_uid}/attachment/{attachment_uid}/name",
                CHANGE_ORDER: "/board/{uid}/card/{card_uid}/attachment/{attachment_uid}/order",
                DELETE: "/board/{uid}/card/{card_uid}/attachment/{attachment_uid}",
            },
            COMMENT: {
                GET_LIST: "/board/{uid}/card/{card_uid}/comments",
                ADD: "/board/{uid}/card/{card_uid}/comment",
                UPDATE: "/board/{uid}/card/{card_uid}/comment/{comment_uid}",
                DELETE: "/board/{uid}/card/{card_uid}/comment/{comment_uid}",
                REACT: "/board/{uid}/card/{card_uid}/comment/{comment_uid}/react",
            },
            CHECKLIST: {
                CREATE: "/board/{uid}/card/{card_uid}/checklist",
                NOTIFY: "/board/{uid}/card/{card_uid}/checklist/{checklist_uid}/notify",
                CHANGE_TITLE: "/board/{uid}/card/{card_uid}/checklist/{checklist_uid}/title",
                CHANGE_ORDER: "/board/{uid}/card/{card_uid}/checklist/{checklist_uid}/order",
                TOGGLE_CHECKED: "/board/{uid}/card/{card_uid}/checklist/{checklist_uid}/toggle-checked",
                DELETE: "/board/{uid}/card/{card_uid}/checklist/{checklist_uid}",
            },
            CHECKITEM: {
                CREATE: "/board/{uid}/card/{card_uid}/checklist/{checklist_uid}/checkitem",
                CHANGE_TITLE: "/board/{uid}/card/{card_uid}/checkitem/{checkitem_uid}/title",
                CHANGE_DEADLINE: "/board/{uid}/card/{card_uid}/checkitem/{checkitem_uid}/deadline",
                CHANGE_ORDER: "/board/{uid}/card/{card_uid}/checkitem/{checkitem_uid}/order",
                CHANGE_STATUS: "/board/{uid}/card/{card_uid}/checkitem/{checkitem_uid}/status",
                TOGGLE_CHECKED: "/board/{uid}/card/{card_uid}/checkitem/{checkitem_uid}/toggle-checked",
                CARDIFY: "/board/{uid}/card/{card_uid}/checkitem/{checkitem_uid}/cardify",
                DELETE: "/board/{uid}/card/{card_uid}/checkitem/{checkitem_uid}",
            },
            SUB_CHECKITEM: {
                CREATE: "/board/{uid}/card/{card_uid}/checkitem/{checkitem_uid}/sub-checkitem",
                CHANGE_ORDER: "/board/{uid}/card/{card_uid}/sub-checkitem/{sub_checkitem_uid}/order",
            },
        },
        WIKI: {
            GET_ALL: "/board/{uid}/wikis",
            GET_DETAILS: "/board/{uid}/wiki/{wiki_uid}",
            CREATE: "/board/{uid}/wiki",
            UPLOAD: "/board/{uid}/wiki/{wiki_uid}/attachment",
            CHANGE_DETAILS: "/board/{uid}/wiki/{wiki_uid}/details",
            CHANGE_ORDER: "/board/{uid}/wiki/{wiki_uid}/order",
            CHANGE_PUBLIC: "/board/{uid}/wiki/{wiki_uid}/public",
            UPDATE_ASSIGNEES: "/board/{uid}/wiki/{wiki_uid}/assignees",
            DELETE: "/board/{uid}/wiki/{wiki_uid}",
        },
        SETTINGS: {
            UPDATE_DETAILS: "/board/{uid}/settings/details",
            EMAIL_NOTIFICATIONS: "/board/{uid}/settings/email-notifications",
            UPDATE_USER_ROLES: "/board/{uid}/settings/roles/user/{user_uid}",
            DELETE_PROJECT: "/board/{uid}/settings/delete",
            LABEL: {
                CREATE: "/board/{uid}/settings/label",
                CHANGE_DETAILS: "/board/{uid}/settings/label/{label_uid}/details",
                CHANGE_ORDER: "/board/{uid}/settings/label/{label_uid}/order",
                DELETE: "/board/{uid}/settings/label/{label_uid}",
            },
            INTERNAL_BOT: {
                CHANGE_BOT: "/board/{uid}/settings/internal-bot",
                CHANGE_SETTINGS: "/board/{uid}/settings/internal-bot/settings",
            },
        },
    },
    BOT: {
        SCOPE: {
            CREATE: "/bot/{bot_uid}/scope",
            APPLY_DEFAULT: "/bot/{bot_uid}/scope/default",
            TOGGLE_TRIGGER_CONDITION: "/bot/{bot_uid}/scope/{scope_uid}/trigger-condition",
            TOGGLE_FREEZE: "/bot/{bot_uid}/scope/{scope_uid}/freeze",
            DELETE: "/bot/{bot_uid}/scope/{scope_uid}",
        },
        SCHEDULE: {
            GET_ALL_BY_PROJECT: "/bot/{bot_uid}/project/{project_uid}/schedules",
            GET_ALL_BY_CARD: "/bot/{bot_uid}/card/{card_uid}/schedules",
            GET_ALL_BY_COLUMN: "/bot/{bot_uid}/column/{project_column_uid}/schedules",
            PROJECT_SCHEDULE: "/projects/{project_uid}/bots/{bot_uid}/schedules",
            PROJECT_RESCHEDULE: "/projects/{project_uid}/bots/{bot_uid}/schedules/{schedule_uid}",
            PROJECT_UNSCHEDULE: "/projects/{project_uid}/bots/{bot_uid}/schedules/{schedule_uid}",
        },
        LOG: {
            GET_ALL_BY_PROJECT: "/bot/{bot_uid}/project/{project_uid}/logs",
            GET_ALL_BY_CARD: "/bot/{bot_uid}/card/{card_uid}/logs",
            GET_ALL_BY_COLUMN: "/bot/{bot_uid}/column/{project_column_uid}/logs",
        },
    },
    METADATA: {
        CARD: "/metadata/project/{uid}/card/{card_uid}",
        PROJECT_CARDS: "/metadata/project/{uid}/cards",
        PROJECT_WIKI: "/metadata/project/{uid}/wiki/{wiki_uid}",
    },
    MCP: {
        GET_TOOL_LIST: "/mcp/tools",
    },
    SETTINGS: {
        GET_SETTING_ROLES: "/settings/roles",
        PROJECT_TEMPLATES: {
            GET_LIST: "/settings/project-templates",
            SET_DEFAULT: "/settings/project-templates/default",
        },
        USERS: {
            GET_LIST: "/settings/users",
            CREATE: "/settings/users",
            UPDATE: "/settings/users/{user_uid}",
            DELETE: "/settings/users/{user_uid}",
            DELETE_SELECTED: "/settings/users",
            UPDATE_SETTING_ROLE: "/settings/users/{user_uid}/setting-role",
            UPDATE_API_KEY_ROLE: "/settings/users/{user_uid}/api-key-role",
            UPDATE_MCP_ROLE: "/settings/users/{user_uid}/mcp-role",
        },
        BOTS: {
            GET_LIST: "/settings/bots",
            CREATE: "/settings/bot",
            ACTION_SUGGESTIONS: "/settings/bot/action-suggestions",
            DRAFT: "/settings/bot/draft",
            COPY: "/settings/bot/{bot_uid}/copy",
            UPDATE: "/settings/bot/{bot_uid}",
            UPDATE_DEFAULT_TRIGGER_CONDITIONS: "/settings/bot/{bot_uid}/default-trigger-conditions",
            GENERATE_NEW_API_TOKEN: "/settings/bot/{bot_uid}/new-api-token",
            DELETE: "/settings/bot/{bot_uid}",
            DEFAULT_SCOPE_BRANCH: {
                GET_LIST: "/settings/bot/{bot_uid}/default-scope-branches",
                CREATE: "/settings/bot/{bot_uid}/default-scope-branch",
                UPDATE: "/settings/bot/default-scope-branch/{default_scope_uid}",
                DELETE: "/settings/bot/default-scope-branch/{default_scope_uid}",
            },
        },
        GLOBAL_RELATIONSHIPS: {
            GET_LIST: "/settings/global-relationships",
            CREATE: "/settings/global-relationship",
            IMPORT: "/settings/import-global-relationships",
            UPDATE: "/settings/global-relationship/{uid}",
            DELETE: "/settings/global-relationship/{uid}",
            DELETE_SELECTED: "/settings/global-relationship",
        },
        INTERNAL_BOTS: {
            GET_LIST: "/settings/internal-bots",
            CREATE: "/settings/internal-bot",
            COPY: "/settings/internal-bot/{bot_uid}/copy",
            UPDATE: "/settings/internal-bot/{bot_uid}",
            CHANGE_DEFAULT: "/settings/internal-bot/{bot_uid}/default",
            DELETE: "/settings/internal-bot/{bot_uid}",
        },
        SCHEMAS: {
            API_LIST: "/schema/api",
            API_COMFORT_TOOLS: "/schema/api/comfort",
            API_COMFORT_TOOL: "/schema/api/comfort/{comfort_tool_name}",
            WEBHOOK: "/schema/webhook.json",
        },
        OLLAMA: {
            HEALTH: "/settings/ollama/health",
            GET_LIST: "/settings/ollama/models",
            GET_DETAILS: "/settings/ollama/model/details",
            GET_RUNNING_LIST: "/settings/ollama/models/running",
        },
        API_KEYS: {
            GET_LIST: "/settings/api-keys",
            GET: "/settings/api-keys/{key_uid}",
            CREATE: "/settings/api-keys",
            UPDATE: "/settings/api-keys/{key_uid}",
            DELETE: "/settings/api-keys/{key_uid}",
            DELETE_SELECTED: "/settings/api-keys",
            ACTIVATE: "/settings/api-keys/{key_uid}/activate",
            DEACTIVATE: "/settings/api-keys/{key_uid}/deactivate",
        },
        MCP_TOOL_GROUPS: {
            GET_ADMIN_LIST: "/settings/mcp/groups/admin",
            GET_GLOBAL_LIST: "/settings/mcp/groups/global",
            CREATE: "/settings/mcp/group",
            UPDATE: "/settings/mcp/group/{group_uid}",
            DELETE: "/settings/mcp/group/{group_uid}",
            DELETE_SELECTED: "/settings/mcp/groups",
            ACTIVATE: "/settings/mcp/group/{group_uid}/activate",
            DEACTIVATE: "/settings/mcp/group/{group_uid}/deactivate",
        },
        WEBHOOKS: {
            GET_LIST: "/settings/webhooks",
            GET: "/settings/webhook/{webhook_uid}",
            CREATE: "/settings/webhook",
            UPDATE: "/settings/webhook/{webhook_uid}",
            DELETE: "/settings/webhook/{webhook_uid}",
            DELETE_SELECTED: "/settings/webhooks",
        },
        NOTIFICATION_SCHEDULE: "/settings/notification-schedule",
        NOTIFICATION_SCHEDULE_RULE: {
            CREATE: "/settings/notification-schedule/rule",
            UPDATE: "/settings/notification-schedule/rule/{rule_uid}",
            DELETE: "/settings/notification-schedule/rule/{rule_uid}",
            DELETE_SELECTED: "/settings/notification-schedule/rules",
        },
    },
    GLOBAL: {
        INTERNAL_BOTS: {
            GET: "/global/internal-bot/{bot_uid}",
        },
    },
} as const;

export const Routing = {
    API,
} as const;
