import { McpToolGroup } from "@/core/models";
import { EHttpStatus } from "@langboard/core/enums";

export const ROUTES = {
    REDIRECT: "/redirect",
    SIGN_IN: {
        EMAIL: "/auth/signin",
        PASSWORD: "/auth/signin/pwd",
        OIDC_CALLBACK: "/auth/oidc/callback",
    },
    SIGN_UP: {
        ROUTE: "/auth/signup",
        REQUIRED: "/auth/signup/required",
        ADDITIONAL: "/auth/signup/additional",
        OPTIONAL: "/auth/signup/optional",
        OVERVIEW: "/auth/signup/overview",
        COMPLETE: "/auth/signup/complete",
        ACTIVATE: "/auth/signup/activate",
    },
    ACCOUNT_RECOVERY: {
        NAME: "/auth/recovery",
        RESET: "/auth/recovery/reset",
    },
    AFTER_SIGN_IN: "/dashboard",
    ACCOUNT: {
        ROUTE: "/account",
        PROFILE: "/account/profile",
        EMAILS: {
            ROUTE: "/account/emails",
            VERIFY: "/account/emails/verify",
        },
        PASSWORD: "/account/password",
        GROUPS: "/account/groups",
        PREFERENCES: "/account/preferences",
    },
    BOARD: {
        ROUTE: "/board",
        INVITATION: "/board/invitation",
        MAIN: (uid: string) => `/board/${uid}`,
        WIKI: (uid: string) => `/board/${uid}/wiki`,
        WIKI_PAGE: (uid: string, wikiUID: string) => `/board/${uid}/wiki/${wikiUID}`,
        WIKI_ACTIVITY: (uid: string, wikiUID: string) => `/board/${uid}/wiki/${wikiUID}/activity`,
        WIKI_METADATA: (uid: string, wikiUID: string) => `/board/${uid}/wiki/${wikiUID}/metadata`,
        SETTINGS: (uid: string) => `/board/${uid}/settings`,
        SETTINGS_PAGE: (uid: string, page: string) => `/board/${uid}/settings/${page}`,
        CARD: (uid: string, cardUID: string) => `/board/${uid}/${cardUID}`,
    },
    DASHBOARD: {
        ROUTE: "/dashboard",
        PAGE_TYPE: (type: string) => `/dashboard/${type}`,
        PROJECTS: {
            ROUTE: "/dashboard/projects",
            TAB: (tab: string) => `/dashboard/projects/${tab}`,
            ALL: "/dashboard/projects/all",
            STARRED: "/dashboard/projects/starred",
            RECENT: "/dashboard/projects/recent",
            UNSTARRED: "/dashboard/projects/unstarred",
        },
        CARDS: "/dashboard/cards",
        TRACKING: "/dashboard/tracking",
    },
    SETTINGS: {
        ROUTE: "/settings",
        API_KEYS: "/settings/api-keys",
        PROJECT_TEMPLATES: "/settings/project-templates",
        USERS: "/settings/users",
        CREATE_USER: "/settings/users/create",
        CREATE_API_KEY: "/settings/api-keys/create",
        BOTS: "/settings/bots",
        CREATE_BOT: "/settings/bots/create",
        BOT_DETAILS: (uid: string) => `/settings/bots/${uid}`,
        INTERNAL_BOTS: "/settings/internal-bots",
        CREATE_INTERNAL_BOT: "/settings/internal-bots/create",
        INTERNAL_BOT_DETAILS: (uid: string) => `/settings/internal-bots/${uid}`,
        GLOBAL_RELATIONSHIPS: "/settings/global-relationships",
        CREATE_GLOBAL_RELATIONSHIP: "/settings/global-relationships/create",
        API_COMFORT_TOOLS: "/settings/api-comfort-tools",
        WEBHOOKS: "/settings/webhooks",
        CREATE_WEBHOOK: "/settings/webhooks/create",
        NOTIFICATION_SCHEDULE: "/settings/notification-schedule",
        OLLAMA: "/settings/ollama",
        PULL_OLLAMA: "/settings/ollama/pull",
        MCP_TOOL_GROUPS: "/settings/mcp",
        CREATE_MCP_TOOL_GROUP: (groupType: (string & {}) | McpToolGroup.TGroupType) => `/settings/mcp/create/${groupType}`,
    },
    ERROR: (code: EHttpStatus | "*") => `/error/${code}`,
} as const;
